//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace лр5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hospital_need_medicine
    {
        public int id_Hospital_need_medicine { get; set; }
        [Required]
        [Display(Name = "Номер лекарства")]
        public int Medicine_idMedicine { get; set; }
        [Required]
        [Display(Name = "Номер больницы")]
        public int Hospital_idHospital { get; set; }
        [Required]
        [Display(Name = "Количество упаковок")]
        public Nullable<int> quantity_of_packs { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
