//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace лр5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.Hospital_need_medicine = new HashSet<Hospital_need_medicine>();
            this.Pharmacy_has_medicine = new HashSet<Pharmacy_has_medicine>();
        }
        [Required]
        [Display(Name = "Номер лекарства")]
        public int idMedicine { get; set; }
        [Required]
        [Display(Name = "Название лекарства")]
        public string name_of_medicine { get; set; }
        [Required]
        [Display(Name = "Фирма-производитель")]
        public string firm_of_medicine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospital_need_medicine> Hospital_need_medicine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pharmacy_has_medicine> Pharmacy_has_medicine { get; set; }
    }
}
