//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace лр5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pharmacy_has_medicine
    {
        public int id_Pharmacy_has_medicine { get; set; }
        [Required]
        [Display(Name = "Номер лекарства")]
        public int Medicine_idMedicine { get; set; }
        [Required]
        [Display(Name = "Номер аптеки")]
        public int Pharmacy_idPharmacy { get; set; }
        [Required]
        [Display(Name = "Количество упаковок")]
        public Nullable<int> quntity_of_packs { get; set; }
        [Required]
        [Display(Name = "Цена за упаковку")]
        public Nullable<int> cost_of_pack { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
